### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [shiqf/dotfiles#1]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`README.md`](https://github.com/shiqf/dotfiles/blob/a925690aae764507444360fe859b39d22a04d076/README.md). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by shiqf** [comment]
ok, I fix it.
